name: SQF Lint

on:
  push:
    branches: [main]
    paths:
      - '**.sqf'
      - '.github/workflows/sqflint.yml'
  pull_request:
    paths:
      - '**.sqf'

jobs:
  sqflint:
    name: Lint SQF files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run SQFLint
        uses: arma-actions/sqflint@master
        with:
          args: --exit e --directory Addons --recursive
